### ISSUE TITLE
Fix Documentation Typo

### ISSUE THREAD

**Issue by knowbee** [instantOS/instantos.github.io#11]
- [This section](https://github.com/instantOS/instantos.github.io/blob/master/download.md#archive) in `download.md` has a typo.

**Comment by paperbenni** [comment]
And what is the typo?

**Comment by knowbee** [comment]
@paperbenni 

ususally

**Comment by rahul-gohil** [comment]
Also roadmap.md has a typo, instead of "updatung", it should be "updating", on the first line.
