### ISSUE TITLE
Slow Downloadspeed at sourceforge.net In EU

### ISSUE THREAD

**Issue by NicTanghe** [instantOS/instantos.github.io#2]
PLz add a release to releases and use github instead as downloadlink.
they have better uploadspeeds. (downloading at 70.KB/s i'm feeling like it's early 2000's here :D

**Comment by paperbenni** [comment]
Here is an osdn link. It's much faster for me at least. But I will also add a github release.

**Comment by paperbenni** [comment]
The new build is put up on GitHub. Sourceforge and OSDN will be used as mirrors, but the main download link will also be a GitHub one. 
https://github.com/instantOS/instantOS/releases/download/beta2/instantos_beta_2.iso
