### ISSUE TITLE
Distro Image Torrent Seedbox

### ISSUE THREAD

**Issue by TensorTom** [instantOS/instantos.github.io#6]
Recommend running rtorrent on a server somewhere in order to provide bandwidth for the distro image torrent. Am currently unable to download via bittorrent because no seeds. It doesn't have to provide a lot of bandwidth, of course. Just enough to always allow for seeding to start happening. rtorrent can limit up/down speeds.

After a bit of searching, here's a seedbox with a free plan up to 4GB storage which may work good (Haven't tested): [sonicseedbox](https://sonicseedbox.com/#pricing)

**Comment by con-f-use** [comment]
We have a small private server, that hopefully takes care of this from beta 5 onward.
