### ISSUE TITLE
Download link on home page still leads to Beta 3

### ISSUE THREAD

**Issue by luphoria** [instantOS/instantos.github.io#9]
I decided I wanted to switch to your firmware as my 6gb of ram was having trouble with Zorin, and it was a wonderful excuse to start using Arch. I clicked the download link on the home page, however it tried to download beta 3. I almost didn't notice until I opened the download manager again and saw it right next to "Beta 4 released."

Beta 4 is correctly linked in the downloads page, but not the index.

**Comment by paperbenni** [comment]
Thanks for bringing this up. 
It's fixed now
